#Base image
MAINTAINER haniokasai <htek@haniokasai.com>

FROM alpine:3.7
# RUN: when image is being built
RUN echo "BUILDING PROCESS"
RUN apk --no-cache add bash vsftpd

RUN mkdir /minecraft
RUN mkdir /minecraft/multiphar
RUN mkdir /minecraft/resources
RUN mkdir /minecraft/bin
RUN mkdir /minecraft/server

#Copy& extract Bin
ADD ./resources/*  /minecraft/resources/
RUN tar zxvf /minecraft/resources/PHP-7.3-Linux-x86_64.tar.gz /minecraft/bin
WORKDIR /minecraft/resources

#FTP prepare
RUN sh pre-FTP.sh

#BDS and Cuberite and ...
RUN sh pre-BE-BDS.sh
RUN sh pre-BE-Cuberite.sh
RUN sh pre-Java-Minecraft.sh
RUN sh pre-Java-Spigot.sh


#PORT
EXPOSE 21
EXPOSE 19132

#Minecraft and FTP
WORKDIR /minecraft/server
CMD sh /minecraft/resources/runsever.sh && /minecraft/resources/runftp.sh
