#Base image
MAINTAINER haniokasai <htek@haniokasai.com>

FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

# RUN: when image is being built
RUN echo "BUILDING PROCESS"
RUN apt update
RUN apt install bash pure-ftpd wget curl git zip

#Make necessary dirs
RUN mkdir /minecraft
RUN mkdir /minecraft/resources
RUN mkdir /minecraft/bin
RUN mkdir /minecraft/server
##These dirs are for PM-MP there should be mounted.
RUN mkdir /minecraft/multiphar
RUN mkdir /minecraft/defaultplugins

#Copy& extract Bin
ADD ./resources/*  /minecraft/resources/
WORKDIR /minecraft/resources

#FTP prepare
RUN sh pre-FTP.sh

#BDS and Cuberite and ...
RUN sh pre-BE-PMMP.sh
RUN sh pre-BE-BDS.sh
RUN sh pre-BE-Cuberite.sh
#RUN sh pre-Java-Minecraft.sh
#RUN sh pre-Java-Spigot.sh


#PORT
##FTP
EXPOSE 21/tcp
##Minecraft
EXPOSE 19132/udp
##Cuberite Admin
EXPOSE 80/tcp


#Minecraft and FTP
WORKDIR /minecraft/server

CMD sh /minecraft/resources/run-Main.sh
